# Generated by Django 4.0.3 on 2022-05-02 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
       
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_val', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=0)),
                ('remarks', models.CharField(max_length=200)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('inv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Barcodeproduct', to='invoice.itemprice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Barcodeservice', to='invoice.itemprice')),
            ],
        ),
    ]
