# Generated by Django 4.0.4 on 2022-05-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cust_barcode', '0002_alter_barcode_product_alter_barcode_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='b_val',
            new_name='bvalue',
        ),
    ]
