# Generated by Django 4.0.4 on 2022-04-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20)),
                ('mbsp_amount', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('validity', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ex_date', models.DateField()),
                ('avl_price', models.IntegerField(default=0)),
                ('avl_point', models.IntegerField(default=0)),
                ('day_ex', models.IntegerField(default=0)),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('msid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membership')),
            ],
        ),
    ]
