# Generated by Django 4.0.4 on 2022-04-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('pincode', models.IntegerField(default=0)),
                ('dob', models.DateTimeField()),
                ('otp', models.IntegerField(default=0)),
                ('customer_service', models.CharField(max_length=30)),
                ('customer_status', models.BooleanField(default=False)),
                ('customer_type', models.CharField(max_length=20)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
