# Generated by Django 4.0.3 on 2022-06-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_dob_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
