# Generated by Django 4.0.3 on 2022-05-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.TextField()),
                ('date', models.CharField(max_length=30)),
                ('remarks', models.TextField(default='None')),
            ],
        ),
    ]
