# Generated by Django 4.0.3 on 2022-04-11 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
       
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=30)),
                ('service', models.CharField(max_length=30)),
                ('cloth_type', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_piece', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(verbose_name=datetime.datetime(2022, 4, 16, 15, 49, 43, 516610))),
                ('price', models.IntegerField(default=0)),
                ('discount_type', models.CharField(max_length=10)),
                ('discount', models.IntegerField(default=0)),
                ('net', models.IntegerField(default=0)),
                ('payment_due', models.IntegerField(default=0)),
                ('paid', models.IntegerField(default=0)),
                ('payment_type', models.IntegerField()),
                ('payment_status', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=30)),
                ('cancel', models.BooleanField(default=False)),
                ('m_price', models.IntegerField(default=0)),
                ('m_point', models.IntegerField(default=0)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
