# Generated by Django 4.0.4 on 2022-05-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemprice',
            old_name='product_type',
            new_name='cust_type',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.IntegerField(default=0),
        ),
    ]
