# Generated by Django 4.0.3 on 2022-04-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_type', models.CharField(max_length=30)),
                ('service', models.CharField(max_length=30)),
                ('product', models.CharField(max_length=30)),
                ('ind_price', models.IntegerField(default=0)),
                ('no_item', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('remarks', models.CharField(max_length=30)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('inv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('ip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.itemprice')),
            ],
        ),
    ]
